# Generated by Django 3.0.3 on 2020-06-03 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('subjects', models.CharField(max_length=90)),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 3, 22, 49, 45, 479793))),
            ],
        ),
        migrations.CreateModel(
            name='email_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 3, 22, 49, 45, 480704))),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
