# Generated by Django 3.0.3 on 2020-06-03 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200603_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 4, 0, 45, 40, 13081)),
        ),
        migrations.AlterField(
            model_name='email_contact',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 4, 0, 45, 40, 14082)),
        ),
    ]
